import { fetchAllPosts, fetchCategories } from '@blog/features';

const SITE = process.env.NEXT_PUBLIC_BLOG_URL ?? 'https://blog.woolta.com';

const NOW = new Date();
const CATEGORY_PRIORITY = 0.5;
const POSTS_PRIORITY = 1;

export async function makeCategoriesSiteMap() {
  const categories = await fetchCategories();

  return wrapSiteMap(
    categories
      .map((category) => makeSiteMapItemXml(`${SITE}/categories/${category.value}`, CATEGORY_PRIORITY))
      .join(''),
  );
}

export async function makePostsSiteMap() {
  const posts = await fetchAllPosts();

  return wrapSiteMap(
    posts
      .map((post) => makeSiteMapItemXml(`${SITE}/categories/${post.categoryNo}/posts/${post.postNo}`, POSTS_PRIORITY))
      .join(''),
  );
}

function makeSiteMapItemXml(url: string, priority: number) {
  return `<url>
        <loc>${url}</loc>
        <lastmod>${NOW.toISOString()}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>${priority}</priority>
    </url>`;
}

function wrapSiteMap(body: string) {
  return `<?xml version="1.0" encoding="utf-8"?>
    <!--Generated by Screaming Frog SEO Spider 9.4-->
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        ${body}
    </urlset>`;
}
